---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/xhiroga/ansible-role-proxmox
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
