---
# 1Password GUI application
- name: Installing {{ onepassword_pre_reqs_debian }} for 1Password
  apt:
    name: "{{ onepassword_pre_reqs_debian }}"
    update_cache: yes
  become: true

# Note: apt-key is deprecated - [第675回 apt\-keyはなぜ廃止予定となったのか：Ubuntu Weekly Recipe｜gihyo\.jp … 技術評論社](https://gihyo.jp/admin/serial/01/ubuntu-recipe/0675)
- name: Add the key for the 1Password apt repository
  apt_key:
    keyring: "{{ onepassword_repo_debian_gpg_key_keyring }}"
    state: present
    url: "{{ onepassword_repo_debian_gpg_key_url }}"
  become: true

- name: Add repository {{ onepassword_repo_debian }}
  apt_repository:
    repo: "{{ onepassword_repo_debian }}"
    filename: "{{ onepassword_app_name }}"
    state: present
    update_cache: yes
  become: true

- name: Install {{ onepassword_app_name }}
  apt:
    name: "{{ onepassword_app_name }}"
    state: present
    update_cache: yes
  become: true

# 1Password CLI
# Cause unknown, but idepotence test fails.
- name: Installing prerequisites for unarchive
  apt:
    name: "{{ onepassword_cli_pre_reqs_debian }}"
    update_cache: yes
  become: true

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Download 1Password CLI
  ansible.builtin.get_url:
    dest: "{{ temp_dir.path }}/op.zip"
    url: "{{ onepassword_cli_url }}"

- name: Unarchive 1Password CLI
  ansible.builtin.unarchive:
    dest: "{{ temp_dir.path }}"
    src: "{{ temp_dir.path }}/op.zip"
    remote_src: yes

- name: Receive keys
  ansible.builtin.command:
    # [gnupg \- gpg: can't import key: "new key but contains no user ID \- skipped" \- Super User](https://superuser.com/questions/1485213/gpg-cant-import-key-new-key-but-contains-no-user-id-skipped)
    cmd: gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys {{ onepassword_key_id }}

- name: Verify op signature
  ansible.builtin.command:
    cmd: gpg --verify {{ temp_dir.path }}/op.sig {{ temp_dir.path }}/op

- name: Move op to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ temp_dir.path }}/op"
    dest: /usr/local/bin/op
    mode: 755
    remote_src: yes
  become: true

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
