[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["Hiroaki Ogasawara <13391129+xhiroga@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ansible = "^7.0.0"
molecule = "3.5.2" # 3.6.0 and 3.6.1 has bug of `molecule login`
molecule-docker = "^1.1.0"
pywinrm = "^0.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
