[project]
name = "homelab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "ansible>=11.1.0",
    "molecule>=24.12.0",
    "molecule-docker>=2.1.0",
]
