collections:
  - name: community.windows

roles:
  - name: cloudalchemy.coredns
  - name: ngetchell.vscode
  - name: pddg.ghq
  - src: "git+https://github.com/andif888/ansible-role-win10-languagepack.git"
  - src: "git+https://github.com/xhiroga/ansible-roles.git"
