services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "${HOST_PORT:-5678}:5678"
    labels: []
    environment:
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  sync:
    image: alpine
    restart: always
    volumes:
      - n8n_data:/data:ro
      - ${SYNC_DIR}:/sync
    entrypoint: >
      sh -c '
        command -v rsync >/dev/null 2>&1 || apk add --no-cache rsync
        while true; do
          echo "[sync] $(date -Iseconds)"
          rsync -a --delete /data/ /sync/ && echo "[sync] done";
          sleep ${SYNC_INTERVAL:-86400};
        done
      '
    depends_on:
      - n8n

volumes:
  n8n_data:
