---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Copy /etc/ssh/sshd_config
      ansible.builtin.copy:
        src: etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        mode: "0644"
      tags: molecule-idempotence-notest

  tasks:
    - name: "Include posix"
      include_role:
        name: "posix"
  vars:
    ssh_user: root
    ssh_authorized_key: https://github.com/xhiroga.keys
