---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Show file
      command: grep '{{ disable_password_authentication }}' '/etc/ssh/sshd_config'
      register: result
    - name: Assert output
      assert:
        that: "'{{ disable_password_authentication }}' in result.stdout"
  vars:
    disable_password_authentication: "PasswordAuthentication no"
