cask_args appdir: "/Applications"
tap "homebrew/autoupdate"

brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"
brew "grep"

brew "act"
brew "asciinema"
brew "aws-cdk"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion"
brew "bfg"
brew "cabocha"
brew "cmake"
brew "deno"
brew "dprint"   # to contribute to polars
brew "duckdb"
brew "ffmpeg"
brew "fnm"
brew "gh"
brew "ghq"
brew "ghostscript"  # to render python turtle
brew "gibo"
brew "git"
brew "gitleaks"
brew "git-lfs"
brew "go"
brew "gomplate"
brew "graphviz"
brew "gnupg"
brew "hdf5" # tensorflow dependency
brew "libpcap" # FreeRTOS simulation
brew "mecab"
brew "mecab-ipadic"
brew "nmap"
brew "node"
brew "openssl"  # tensorflow dependency
brew "peco"
brew "pnpm"
brew "pre-commit"
# Linux ps command can not be imported to OSX, https://apple.stackexchange.com/questions/187783/can-i-use-gnu-ps-on-os-x
brew "psgrep"
brew "pstree"
brew "pueue"
brew "brew install runpod/runpodctl/runpodctl"
brew "rustup"
brew "shellcheck"
brew "swig" # gymnasium[box2d] dependency
brew "telnet"
brew "tmux"
brew "tree"
brew "uv"
brew "wget"
brew "xz"
brew "yarn"
brew "zlib" # tensorflow dependency

cask "1password-cli"
# cask "dbeaver-community"
cask "discord"
cask "google-cloud-sdk"
# cask "google-japanese-ime"    # When using, "Cannot start conversaion engine." error occurs.
cask "imageoptim"
cask "kindle"
cask "karabiner-elements"
cask "microsoft-edge"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "raycast"
cask "spotify"
cask "wireshark"
cask "zoom"
cask "zotero"

# manually managed softwares
# - Clip Studio Paint (clip-studio-paint) # Homebrew version is 2.3.4 but the latest is 3.0.2
# - GitHub Desktop (github) # Manually installed and Homebrew installed will be conflicted
# - OneDrive (onedrive) # should be installed from AppStore
# - WacomTablet macOS Driver
