---
- name: Install microk8s
  community.general.snap:
    name: microk8s
    channel: latest/edge/strict
    classic: true

# To avoid below error
# Insufficient permissions to access MicroK8s.
# You can either try again with sudo or add the user hiroga to the 'microk8s' group:
#
#     sudo usermod -a -G microk8s hiroga
#     sudo chown -f -R hiroga ~/.kube
#
# After this, reload the user groups either via a reboot or by running 'newgrp microk8s'.
- name: Add users to group.
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  loop: "{{ microk8s_users }}"
  become: true

# In my case, using newgrp looks pause process.
# [You can use an \(ansible\.builtin\.\)meta: reset\_connection task:](https://stackoverflow.com/questions/26677064/create-and-use-group-without-restart)
- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection

# [Getting started with MicroK8s on Ubuntu Core \| Ubuntu](https://ubuntu.com/tutorials/getting-started-with-microk8s-on-ubuntu-core)
- name: Enable plugins
  ansible.builtin.command:
    cmd: "microk8s.enable {{ item }}"
  loop: "{{ microk8s_plugins }}"
  become: true
