FROM geerlingguy/docker-ubuntu2004-ansible
# gcc and libreadline-dev is required to build ruby
# unzip and zip is required to unpack sdkman
RUN apt update && sudo apt install curl gcc git libreadline-dev unzip zip -y
