all:
  children:
    macos:
      hosts:
        mbp:
          ansible_connection: local
          ansible_host: localhost
    rtx1210:
      hosts: 192.168.100.1
    proxmox:
      hosts: hiroga-proxmox
    diskstation:
      hosts: ds218play
    ubuntu_dev:
      hosts: hiroga-udon
    winrm:
      hosts:
        hiroga-wasabi-winrm
    windows_dev:
      hosts:
        # hiroga-wasabi
        wsl-host
