all:
  children:
    macos:
      hosts:
        mbp:
          ansible_connection: local
          ansible_host: localhost
    rtx1210:
      hosts: 192.168.100.1
    proxmox:
      hosts: pve
    diskstation:
      hosts: ds218play
    ubuntu_dev:
      hosts: udon
    win_gpu:
      hosts:
        HIROGA-RTX4090
    win_vm:
      hosts:
        walnut
    win_vm_gpu:
      hosts:
        wasabi
    wsl:
      hosts:
        HIROGA-RTX4090-wsl:
          ansible_connection: local
          ansible_host: localhost
