all:
  children:
    macos:
      hosts:
        mbp:
          ansible_connection: local
          ansible_host: localhost
    rtx1210:
      hosts: 192.168.100.1
    proxmox:
      hosts: pve
    diskstation:
      hosts: ds218play
    ubuntu_dev:
      hosts: hiroga-udon
    win_gpu:
      hosts:
        wasabi
    win:
      hosts:
        surface-go
    wsl:
      hosts: 
        surface-go-wsl:
          ansible_connection: local
          ansible_host: localhost
