all:
  children:
    macos:
      hosts:
        MacBook:
          ansible_connection: local
          ansible_host: localhost
    rtx1210:
      hosts: 192.168.100.1
    proxmox:
      hosts: pve
    diskstation:
      hosts: ds218play
    ubuntu_vm:
      hosts: udon
    windows:
      hosts:
        hiroga-rtx4090
    wsl:
      hosts:
        wsl.hiroga-rtx4090:
          ansible_connection: local
          ansible_host: localhost
