---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test anyenv installed
      ansible.builtin.shell: "$HOME/.anyenv/bin/anyenv --version"
    - name: Test pyenv installed
      ansible.builtin.shell: |
        export PATH=$HOME/.anyenv/bin:$PATH
        eval "$(anyenv init -)"
        pyenv --version
    - name: Test Rust and Cargo installed
      ansible.builtin.shell: "$HOME/.cargo/bin/cargo --version "
