ansible_connection: ssh
ansible_shell_type: powershell

winget_packages:
  - "AgileBits.1Password"
  - "Anaconda.Miniconda3"
  # - "Discord.Discord" # Not works on 2023-12-25
  - "GitHub.GitHubDesktop"
  - "Git.Git"
  - "GitHub.GitLFS"
  # - "Google.JapaneseIME"
  - "Microsoft.VisualStudioCode"
  - "Obsidian.Obsidian"
  - "OBSProject.OBSStudio"
  - "SlackTechnologies.Slack"
  - "Sysinternals Suite"
  - "Valve.Steam"
