ansible_connection: ssh
ansible_shell_type: powershell

winget_packages:
  - "AgileBits.1Password"
  # - "Discord.Discord" # Not works on 2023-12-25
  - "GitHub.GitHubDesktop"
  - "Git.Git"
  - "Microsoft.VisualStudioCode"
  - "Valve.Steam"
