- name: Configure static ip
  ansible.builtin.template:
    src: ./templates/etc/netplan/99_config.yaml.j2
    dest: /etc/netplan/99_config.yaml
  become: true

- name: Apply netplan
  ansible.builtin.shell: netplan apply
  become: true
