---
# tasks file for windows
- name: Modify Registry
  ansible.windows.win_regedit:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: '{{ item.datatype | default("dword") }}'
  with_items:
    - key: HKCU:\SOFTWARE\Microsoft\Clipboard
      value: EnableClipboardHistory
      data: 1
      type: dword
    # [How to toggle Show/Hide hidden files in Windows through command line? \- Super User](https://superuser.com/questions/1151844/how-to-toggle-show-hide-hidden-files-in-windows-through-command-line)
    - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      value: Hidden
      data: 1
      type: dword
    # エクスプローラーの「登録されている拡張子は表示しない」の無効化
    - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      value: HideFileExt
      data: 0
    # [powershell - Enable Windows 10 Developer Mode programmatically - Stack Overflow](https://stackoverflow.com/questions/40033608/enable-windows-10-developer-mode-programmatically)
    # [Support portable packages in user mode without Developer Mode enabled · Issue #2368 · microsoft/winget-cli](https://github.com/microsoft/winget-cli/issues/2368)
    - key: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
      value: AllowDevelopmentWithoutDevLicense
      data: 1
      type: dword
    - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShowFrequent
      value: HideFileExt
      data: 0
    - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShowRecent
      value: HideFileExt
      data: 0
    # TODO: タスクバーのタスクビュー、ウィジェット、チャットの非表示化
    # TODO: Disable Window Snap <https://atmarkit.itmedia.co.jp/ait/articles/1904/18/news027.html>
    # TODO: https://qiita.com/Oscer/items/132a8153cc5dcf0fad47
    # TODO: LongPathEnabled
    # TODO: Use Unicode UTF-8 https://qiita.com/misohagi/items/e26c589506a69261fe04
    - key: HKLM:\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Sudo
      value: Enabled
      data: 1

# - name: Enable File and Printer Sharing
#   ansible.windows.win_command: netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=Yes

# - name: Enable Network Discovery
#   ansible.windows.win_command: netsh advfirewall firewall set rule group="Network Discovery" new enable=Yes

# - name: Restart Explorer
#   ansible.windows.win_shell: stop-process -name explorer -force

- name: List winget packages
  # ansible.windows.win_shell: win-get list
  ansible.windows.win_shell: Invoke-Expression "& '$(Join-Path (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation "winget.exe")' list" # https://github.com/microsoft/winget-cli/issues/1474#issuecomment-1249701447
  register: winget_list

# アプリケーション実行時にインストールするとエラーになることが多いので、初回に限る。
- name: Install packages
  # In the first time, manually put [Y] Yes to agreements terms.
  # ansible.windows.win_shell: winget install {{ item }}
  ansible.windows.win_shell: Invoke-Expression "& '$(Join-Path (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation "winget.exe")' install {{ item }}" # https://github.com/microsoft/winget-cli/issues/1474#issuecomment-1249701447
  loop: "{{ winget_packages }}"
  when: item not in winget_list.stdout

- name: Ensure user variables for hiroga
  ansible.windows.win_path:
    elements: "{{ win_path_user_elements }}"
    name: 'Path'
    scope: user

- name: Ensure machine variables
  ansible.windows.win_path:
    elements: "{{ win_path_machine_elements }}"
    name: 'Path'
    scope: machine

- name: SSH port forwarding for WSL2
  include_tasks: wsl2-ssh-port-forward.yml

# git config --global --add --bool push.autoSetupRemote true
