---
- name: Install build-essential
  ansible.builtin.apt:
    name:
      - build-essential
    state: present
  become: true

- name: Install pkg-config, libxml2 and libxml2-dev
  ansible.builtin.apt:
    name:
      - pkg-config
      # LIBXML2
      - libxml2
      - libxml2-dev
      # freetype2
      - libfreetype6
      - libfreetype6-dev
      # FONTCONFIG
      - fontconfig
      - libfontconfig1-dev
      # ANT
      - ant
      # Development tools
      - clang
      - git-lfs
    state: present
  become: true

- name: Add ppa:deadsnakes/ppa
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  become: true

- name: Install Python
  ansible.builtin.apt:
    name:
      - python3.8
      - python3.8-venv
      - python3.9
      - python3.9-venv
      - python3.10
      - python3.10-venv
    state: present
  become: true

- name: Install from Brewfile
  ansible.builtin.shell: brew bundle --file={{ item }}
  with_items:
    - "{{ homebrew_brewfile_dir }}/Brewfile"

# TODO: ボリュームをマウントする。
# https://claude.ai/chat/9e9cfd8e-925e-4c82-86d6-f731beb36c41
