---
- name: Copy private key to the remote server
  copy:
    src: ~/.ssh/id_ed25519_dev
    dest: ~/.ssh/id_ed25519
    mode: '0600'

- name: Copy public key to the remote server
  copy:
    src: ~/.ssh/id_ed25519_dev.pub
    dest: ~/.ssh/id_ed25519.pub
    mode: '0644'

- name: Add SSH config for GitHub
  blockinfile:
    path: ~/.ssh/config
    create: yes
    block: |
      Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/id_ed25519
          IdentitiesOnly yes
    mode: '0600'

- name: Ensure known_hosts file exists
  file:
    path: ~/.ssh/known_hosts
    state: touch
    mode: '0644'

# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
# https://huggingface.co/docs/hub/en/security-git-ssh
- name: Add GitHub's public key to known_hosts
  known_hosts:
    path: ~/.ssh/known_hosts
    name: github.com
    key: |
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      hf.co ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJjhgtT9FOQrsVSarIoPVI1jFMh3VSHdKfdqp/O776s

- name: Test SSH connection to GitHub
  command: ssh -T git@github.com
  register: ssh_test_output
  ignore_errors: yes

- name: Display SSH test result
  debug:
    msg: "{{ ssh_test_output.stdout }}"

- name: Copy .gitconfig template to user home
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "~/.gitconfig"
    mode: '0644'
