n8n-borzoi-up:
	docker compose -f n8n/docker-compose.yml -p n8n-borzoi --env-file config/.n8n-borzoi.env up -d
n8n-borzoi-stop:
	docker compose -f n8n/docker-compose.yml -p n8n-borzoi stop

n8n-yagi-up:
	docker compose -f n8n/docker-compose.yml -p n8n-yagi --env-file config/.n8n-yagi.env up -d
n8n-yagi-stop:
	docker compose -f n8n/docker-compose.yml -p n8n-yagi stop
