---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check gpg file exists
    stat:
      path: /usr/share/keyrings/1password-archive-keyring.gpg
    register: gpg_file_result

  - name: Assert gpg file exists
    assert:
      that: gpg_file_result

  - name: Check source list exists
    stat:
      path: /etc/apt/sources.list.d/1password.list
    register: source_list_result

  - name: Assert source list exists
    assert:
      that: source_list_result

  - name: Check op is executable
    ansible.builtin.command:
      cmd: op
