- name: Check bun stats
  ansible.builtin.stat:
    path: $HOME/.bun/bin/bun
  register: bun

- name: Install bun
  ansible.builtin.shell: curl https://bun.sh/install | bash
  when: not bun.stat.exists

- name: Upgrade bun
  ansible.builtin.shell: $HOME/.bun/bin/bun upgrade
  when: bun.stat.exists
