# [Cannot install ruby through rbenv @ macOS 12\.3 · Issue \#98 · anyenv/anyenv](https://github.com/anyenv/anyenv/issues/98)
---
- name: Ensure rbenv installed
  ansible.builtin.shell: rbenv --version
  args: { executable: /bin/bash }
  changed_when: false
  ignore_errors: true
  register: has_rbenv

- name: Install rbenv by brew
  ansible.builtin.shell: brew install rbenv
  when: has_rbenv.rc == 1 and has_brew_version.rc != 127

- name: Install rbenv
  ansible.builtin.shell: sudo apt install rbenv
  when: has_rbenv.rc == 1 and has_brew_version.rc == 127

- name: Install rbenv versions
  ansible.builtin.shell: rbenv install -s {{ item }}
  loop: "{{ rbenv_versions }}"
  changed_when: false

- name: Configure rbenv global version
  ansible.builtin.shell: rbenv global {{ rbenv_global_version }}
  changed_when: false
