## References
# [Install Rust \- Rust Programming Language](https://www.rust-lang.org/tools/install)
---
- name: Install rust
  shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  changed_when: false
