#!/bin/sh ansible-playbook
---
- name: Configure WSL
  hosts: 'wsl'
  pre_tasks:
    - name: Check kernel type
      command: "uname -m"
  roles:
    - role: wsl
    - role: geerlingguy.mac.homebrew
      becore: true
  #   - role: dotfiles
