#!/bin/sh ansible-playbook
---
- name: Configure WSL
  hosts: 'wsl'
  gather_facts: true
  pre_tasks:
    - name: Check kernel type
      command: "uname -m"
  roles:
    - role: wsl
    - role: dotfiles
